(function () {
    "use strict";
    const HND_HISTORICAL_DB_NAME="HNDaiBacktestData", HND_HISTORICAL_DB_VERSION=1;
    const HND_HISTORICAL_DATASET_STORE="datasets", HND_HISTORICAL_MAX_CACHE_DATASETS=10;
    const HND_HISTORICAL_MAX_CACHE_BYTES=128*1024*1024;
    let initialized=false,db=null,persistenceAvailable=false,lastEvaluation=null;
    const memory=new Map();
    function cloneHistoricalDataset(dataset){if(!dataset)return null;const columns={};for(const key of ["openTime","open","high","low","close","volume","closeTime"]){if(!(dataset.columns?.[key] instanceof Float64Array))return null;columns[key]=new Float64Array(dataset.columns[key]);}return{metadata:{...dataset.metadata},columns};}
    function debug(reason,error=null){lastEvaluation={debug:{primaryReason:reason,persistenceAvailable,storageMode:persistenceAvailable?"INDEXEDDB":"MEMORY",errorName:error?String(error.name||"Error"):null,errorMessage:error?String(error.message||error).slice(0,200):null,evaluatedAt:Date.now()}};}
    function requestPromise(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error("IndexedDB request failed"));});}
    function openDb(){return new Promise((resolve,reject)=>{if(typeof indexedDB==="undefined")return reject(new Error("IndexedDB unavailable"));const request=indexedDB.open(HND_HISTORICAL_DB_NAME,HND_HISTORICAL_DB_VERSION);request.onupgradeneeded=()=>{const database=request.result;const store=database.objectStoreNames.contains(HND_HISTORICAL_DATASET_STORE)?request.transaction.objectStore(HND_HISTORICAL_DATASET_STORE):database.createObjectStore(HND_HISTORICAL_DATASET_STORE,{keyPath:"cacheKey"});for(const name of ["lastAccessedAt","fetchedAt","symbol","interval"]){if(!store.indexNames.contains(name))store.createIndex(name,name,{unique:false});}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||new Error("IndexedDB open failed"));});}
    async function init(){if(initialized)return getState();initialized=true;try{db=await openDb();persistenceAvailable=true;debug("INDEXEDDB_READY");}catch(error){persistenceAvailable=false;debug("INDEXEDDB_UNAVAILABLE",error);}return getState();}
    async function records(){if(!persistenceAvailable)return[...memory.values()].map(cloneHistoricalDataset);const tx=db.transaction(HND_HISTORICAL_DATASET_STORE,"readonly"),store=tx.objectStore(HND_HISTORICAL_DATASET_STORE);return(await requestPromise(store.getAll())).map(record=>cloneHistoricalDataset({metadata:record.metadata,columns:record.columns}));}
    async function getDataset(cacheKey){await init();let dataset;if(persistenceAvailable){const tx=db.transaction(HND_HISTORICAL_DATASET_STORE,"readonly"),record=await requestPromise(tx.objectStore(HND_HISTORICAL_DATASET_STORE).get(cacheKey));dataset=record?{metadata:record.metadata,columns:record.columns}:null;}else dataset=memory.get(cacheKey)||null;if(!dataset)return null;dataset=cloneHistoricalDataset(dataset);dataset.metadata.lastAccessedAt=Date.now();if(persistenceAvailable){const tx=db.transaction(HND_HISTORICAL_DATASET_STORE,"readwrite");tx.objectStore(HND_HISTORICAL_DATASET_STORE).put({cacheKey,...dataset});}else memory.set(cacheKey,cloneHistoricalDataset(dataset));return cloneHistoricalDataset(dataset);}
    async function enforceLru(protectedKey){const list=await records();let bytes=list.reduce((s,d)=>s+(Number(d.metadata.estimatedBytes)||0),0);list.sort((a,b)=>(a.metadata.lastAccessedAt||0)-(b.metadata.lastAccessedAt||0));while((list.length>HND_HISTORICAL_MAX_CACHE_DATASETS||bytes>HND_HISTORICAL_MAX_CACHE_BYTES)&&list.length>1){const index=list.findIndex(d=>d.metadata.cacheKey!==protectedKey);if(index<0)break;const victim=list.splice(index,1)[0];bytes-=Number(victim.metadata.estimatedBytes)||0;await deleteDataset(victim.metadata.cacheKey);}}
    async function putDataset(dataset){await init();const copy=cloneHistoricalDataset(dataset);if(!copy||!copy.metadata?.cacheKey)throw new TypeError("Invalid historical dataset");copy.metadata.lastAccessedAt=Date.now();if(persistenceAvailable){const tx=db.transaction(HND_HISTORICAL_DATASET_STORE,"readwrite");await requestPromise(tx.objectStore(HND_HISTORICAL_DATASET_STORE).put({cacheKey:copy.metadata.cacheKey,...copy}));}else memory.set(copy.metadata.cacheKey,cloneHistoricalDataset(copy));try{await enforceLru(copy.metadata.cacheKey);}catch(error){debug("LRU_CLEANUP_FAILED",error);}debug("DATASET_STORED");return cloneHistoricalDataset(copy);}
    async function deleteDataset(cacheKey){await init();if(persistenceAvailable){const tx=db.transaction(HND_HISTORICAL_DATASET_STORE,"readwrite");await requestPromise(tx.objectStore(HND_HISTORICAL_DATASET_STORE).delete(cacheKey));}else memory.delete(cacheKey);return true;}
    async function clearAll(){await init();if(persistenceAvailable){const tx=db.transaction(HND_HISTORICAL_DATASET_STORE,"readwrite");await requestPromise(tx.objectStore(HND_HISTORICAL_DATASET_STORE).clear());}memory.clear();return true;}
    async function listDatasets(){const list=await records();return list.map(d=>({...d.metadata})).sort((a,b)=>(b.lastAccessedAt||0)-(a.lastAccessedAt||0));}
    async function getState(){const list=initialized?await listDatasets().catch(()=>[]):[];return{initialized,persistenceAvailable,storageMode:persistenceAvailable?"INDEXEDDB":"MEMORY",datasetCount:list.length,estimatedTotalBytes:list.reduce((s,m)=>s+(Number(m.estimatedBytes)||0),0),datasets:list,lastEvaluation:JSON.parse(JSON.stringify(lastEvaluation))};}
    function getLastDebug(){return lastEvaluation?{...lastEvaluation.debug}:null;}function explainLastEvaluation(){return lastEvaluation?JSON.parse(JSON.stringify(lastEvaluation)):null;}
    window.HNDHistoricalDataStore={init,getDataset,putDataset,deleteDataset,clearAll,listDatasets,getState,getLastDebug,explainLastEvaluation};
    window.HNDCloneHistoricalDataset=cloneHistoricalDataset;
})();
