"use strict";
self.window = self;
var candles = [], currentPrice = 0, clockMs = 0, forbiddenNetworkCallCount = 0;
var control = { requestId: null, paused: false, cancelled: false, resume: null };
self.fetch = function () { forbiddenNetworkCallCount++; throw new Error("FORBIDDEN_NETWORK_CALL"); };
try { Object.defineProperty(self, "localStorage", { get: function () { throw new Error("STORAGE_FORBIDDEN"); } }); } catch (_) {}
importScripts("indicators.js", "smartmoney.js", "strategy.js", "setupEngine.js", "tradePlanEngine.js", "tradeEngine.js");

var WINDOW_BARS = 500, WARMUP_BARS = 500, CHUNK_BARS = 20, CHECKPOINT_BARS = 100, MAX_TRADES = 1000;
var HND_PARITY_PROFILE_VERSION = "HND-LIVE-REPLAY-PARITY-V1";
var HND_PARITY_RULESET_FINGERPRINT = "EB573423E9475944F0956BB88C7B102B419473A5BDE9A97662D4D6B5EA67BBE9";
var STRIP_KEYS = new Set(["debug", "lastEvaluation", "requestId", "durationMs", "candlesPerSecond", "evaluatedAt", "capturedAt", "completedAt", "updatedAt", "lastAccessedAt"]);
function post(type, requestId, payload) { self.postMessage(Object.assign({ type: type, requestId: requestId, timestamp: Date.now() }, payload || {})); }
function copy(value) { return value == null ? value : JSON.parse(JSON.stringify(value)); }
function finite(value) { var n = Number(value); return Number.isFinite(n) ? n : null; }
function sanitize(value, seen) {
    if (value == null) return null;
    if (["string", "boolean"].includes(typeof value)) return value;
    if (typeof value === "number") return Number.isFinite(value) ? Number(value.toPrecision(15)) : null;
    if (["function", "undefined", "symbol"].includes(typeof value)) return undefined;
    seen = seen || new WeakSet(); if (seen.has(value)) return null; seen.add(value);
    if (Array.isArray(value)) return value.map(function (item) { var clean = sanitize(item, seen); return clean === undefined ? null : clean; });
    var result = {}; Object.keys(value).sort().forEach(function (key) {
        if (STRIP_KEYS.has(key)) return; var clean = sanitize(value[key], seen); if (clean !== undefined) result[key] = clean;
    }); return result;
}
function canonical(value) {
    if (value === null || value === undefined) return "null";
    if (typeof value === "number") return Number.isFinite(value) ? value.toPrecision(15) : "null";
    if (typeof value === "string" || typeof value === "boolean") return JSON.stringify(value);
    if (Array.isArray(value)) return "[" + value.map(canonical).join(",") + "]";
    return "{" + Object.keys(value).sort().map(function (key) { return JSON.stringify(key) + ":" + canonical(value[key]); }).join(",") + "}";
}
function hash(value) { var text = canonical(value), h = 2166136261; for (var i = 0; i < text.length; i++) h = Math.imul(h ^ text.charCodeAt(i), 16777619) >>> 0; return h.toString(16).padStart(8, "0").toUpperCase(); }
function checksumCandles(list) { return hash(list.map(function (c) { return [c.time,c.open,c.high,c.low,c.close,c.volume,c.closeTime]; })); }
function seededRandom(seedText) { var seed = parseInt(hash(seedText), 16) >>> 0; return function () { seed += 0x6D2B79F5; var t = seed; t = Math.imul(t ^ t >>> 15, t | 1); t ^= t + Math.imul(t ^ t >>> 7, t | 61); return ((t ^ t >>> 14) >>> 0) / 4294967296; }; }
function normalizeAnalysis(a) { a = a || {}; return sanitize({ signal:a.signal??null, trend:a.trend??null, confidence:finite(a.confidence), rawConfidence:finite(a.rawConfidence), bullScore:finite(a.bullScore), bearScore:finite(a.bearScore), dominantScore:finite(a.dominantScore), opposingScore:finite(a.opposingScore), marketStrength:finite(a.marketStrength), conflictScore:finite(a.conflictScore), scoreDifference:finite(a.scoreDifference), marketBias:a.marketBias??null, ema20:finite(a.ema20), ema50:finite(a.ema50), ema200:finite(a.ema200), rsi:finite(a.rsi), breakdown:a.breakdown??null, evidence:a.evidence??null }); }
function liveOutput(profile) {
    var structure = detectStructureEvents({lookback:3,limit:profile.structureHistoryLimit,includeBOS:true,includeCHoCH:true});
    var liquidity = detectLiquidityZones({lookback:3,tolerance:0.0015,minTouches:2,limit:20,includeSwept:true,includeBroken:false});
    var strongest = getStrongestLiquidityZones(liquidity);
    var obs = detectOrderBlocks({limit:profile.rawZoneHistoryLimit,includeInvalidated:true});
    var fvgs = detectFVGs({limit:profile.rawZoneHistoryLimit,includeInvalidated:true});
    var qualified = selectStructureConfirmedPriceZones({candles:candles,structureEvents:structure,orderBlocks:obs,fvgs:fvgs},copy(profile.structureQualificationOptions));
    var normalized = {analysis:normalizeAnalysis(analyzeMarket()),structure:sanitize(structure),liquidity:sanitize(liquidity),strongestLiquidity:sanitize(strongest),qualifiedOrderBlocks:sanitize(qualified.orderBlocks||[]),qualifiedFVGs:sanitize(qualified.fvgs||[])};
    var fingerprints = {}; Object.keys(normalized).forEach(function(k){ fingerprints[k]=hash(normalized[k]); }); fingerprints.combined=hash(fingerprints);
    return { candleChecksum:checksumCandles(candles), normalized:normalized, fingerprints:fingerprints };
}
function mismatch(layer,path,expected,actual,index,time){return {layer:layer,path:path,expectedType:expected===null?"null":Array.isArray(expected)?"array":typeof expected,actualType:actual===null?"null":Array.isArray(actual)?"array":typeof actual,expected:expected,actual:actual,candleIndex:index??null,candleTime:time??null};}
function compare(expected,actual,layer,path,out,total){
    if(typeof expected==="number"&&typeof actual==="number"&&Number.isFinite(expected)&&Number.isFinite(actual)&&Math.abs(expected-actual)<=1e-10*Math.max(1,Math.abs(expected),Math.abs(actual)))return;
    if(expected===actual)return;
    if(Array.isArray(expected)&&Array.isArray(actual)){if(expected.length!==actual.length){total.count++;if(out.length<50)out.push(mismatch(layer,path+".length",expected.length,actual.length));}var n=Math.max(expected.length,actual.length);for(var i=0;i<n;i++)compare(expected[i],actual[i],layer,path+"["+i+"]",out,total);return;}
    if(expected&&actual&&typeof expected==="object"&&typeof actual==="object"){var keys=Array.from(new Set(Object.keys(expected).concat(Object.keys(actual)))).sort();keys.forEach(function(k){compare(expected[k],actual[k],layer,path?path+"."+k:k,out,total);});return;}
    total.count++;if(out.length<50){var match=path.match(/(?:candleIndex|\[(\d+)\])/);out.push(mismatch(layer,path,expected,actual,match&&match[1]?Number(match[1]):null,null));}
}
function validateLive(message){
    if(message.rulesetFingerprint!==HND_PARITY_RULESET_FINGERPRINT)throw new Error("RULESET_FINGERPRINT_MISMATCH");
    candles=copy(message.capture.candles);currentPrice=Number(message.capture.currentPrice);var actual=liveOutput(message.replayProfile), expected={candleChecksum:message.capture.candleChecksum,normalized:message.capture.normalized,fingerprints:message.capture.fingerprints};
    var details=[],total={count:0};compare(expected.candleChecksum,actual.candleChecksum,"LIVE","candleChecksum",details,total);["analysis","structure","liquidity","strongestLiquidity","qualifiedOrderBlocks","qualifiedFVGs"].forEach(function(k){compare(expected.fingerprints[k],actual.fingerprints[k],"LIVE_"+k.toUpperCase(),"fingerprints."+k,details,total);if(expected.fingerprints[k]!==actual.fingerprints[k])compare(expected.normalized[k],actual.normalized[k],"LIVE_"+k.toUpperCase(),"normalized."+k,details,total);});
    post("LIVE_PARITY_COMPLETED",message.requestId,{result:{status:total.count?"LIVE_STATELESS_PARITY_FAIL":"LIVE_STATELESS_PARITY_PASS",captureId:message.capture.captureId,symbol:message.capture.symbol,interval:message.capture.interval,candleChecksum:message.capture.candleChecksum,profileVersion:HND_PARITY_PROFILE_VERSION,rulesetFingerprint:HND_PARITY_RULESET_FINGERPRINT,validatedAt:Date.now(),mismatchCount:total.count,mismatches:details,expected:expected,actual:actual,forbiddenNetworkCallCount:forbiddenNetworkCallCount}});
}
function stateName(s,f){return String(s?.status||s?.state||f);} function transition(kind,index,columns,previous,next,data){return Object.assign({kind:kind,candleIndex:index,candleTime:columns.openTime[index],previousState:previous,nextState:next},data||{});}
function resetEngines(){candles=[];currentPrice=0;window.HNDSetupEngine.reset("PARITY_REFERENCE_START");window.HNDTradePlanEngine.reset("PARITY_REFERENCE_START");window.HNDTradeEngine.reset("PARITY_REFERENCE_START");window.HNDTradeEngine.clearHistory?.();}
function terminalIdentity(t){return [t?.id,t?.closedAt,t?.state,t?.exitPrice].join("|");}
function collectTerminal(state,c){var t=state?.lastClosedTrade;if(!t||!["CLOSED_TP","CLOSED_SL","CANCELLED_MARKET_CHANGE","CANCELLED_MANUAL"].includes(t.state))return;var id=terminalIdentity(t);if(c.seen.has(id))return;c.seen.add(id);c.total++;if(t.state==="CLOSED_TP")c.tp++;if(t.state==="CLOSED_SL")c.sl++;if(String(t.state).startsWith("CANCELLED"))c.cancelled++;if(["CLOSED_TP","CLOSED_SL"].includes(t.state)){c.netR+=Number(t.realizedR)||0;if(t.direction==="LONG")c.longClosed++;if(t.direction==="SHORT")c.shortClosed++;}if(c.trades.length<MAX_TRADES)c.trades.push(copy(t));}
function normalizeTrade(t,map){var oi=map.get(t.openedAtCandleTime),ci=map.get(t.closedAtCandleTime);return{id:t.id??null,planKey:t.planKey??null,setupKey:t.setupKey??null,symbol:t.symbol??null,interval:t.interval??null,direction:t.direction??null,entryPrice:finite(t.entryPrice),stopLoss:finite(t.stopLoss),takeProfit:finite(t.takeProfit),openedAt:finite(t.openedAt),fillSource:t.fillSource??null,openedAtCandleTime:finite(t.openedAtCandleTime),openedAtCandleIndex:Number.isInteger(oi)?oi:null,closedAt:finite(t.closedAt),closedAtCandleTime:finite(t.closedAtCandleTime),closedAtCandleIndex:Number.isInteger(ci)?ci:null,exitPrice:finite(t.exitPrice),exitReason:t.exitReason??null,exitSource:t.exitSource??null,state:t.state??null,realizedPricePnL:finite(t.realizedPricePnL),realizedR:finite(t.realizedR),maximumFavorableR:finite(t.maxFavorableR),maximumAdverseR:finite(t.maxAdverseR),durationBars:Number.isInteger(oi)&&Number.isInteger(ci)?Math.max(0,ci-oi):null};}
function waitResume(id){if(!control.paused)return Promise.resolve();post("PAUSED",id);return new Promise(function(resolve){control.resume=resolve;}).then(function(){if(control.cancelled)throw Object.assign(new Error("cancelled"),{name:"AbortError"});post("RESUMED",id);});}
function yieldLoop(){return new Promise(function(resolve){setTimeout(resolve,0);});}
async function referenceRun(message,repetition){
    var id=message.requestId,columns=message.columns,profile=message.replayProfile,count=message.config.selectedCandleCount;resetEngines();clockMs=columns.closeTime[0];Date.now=function(){return clockMs;};Math.random=seededRandom(message.datasetMetadata.selectedChecksum+"|DETERMINISTIC");
    var setupEvents=[],planEvents=[],tradeEvents=[],checkpoints=[],collector={trades:[],seen:new Set(),total:0,tp:0,sl:0,cancelled:0,netR:0,longClosed:0,shortClosed:0},map=new Map();for(var g=0;g<count;g++)map.set(columns.openTime[g],g);
    var prevSetup=window.HNDSetupEngine.getState(),prevPlan=window.HNDTradePlanEngine.getState(),prevTrade=window.HNDTradeEngine.getState();post("REPETITION_STARTED",id,{repetition:repetition});var evaluated=0;
    for(var index=WARMUP_BARS-1;index<count;index++){
        if(control.cancelled)throw Object.assign(new Error("cancelled"),{name:"AbortError"});if(evaluated&&evaluated%CHUNK_BARS===0){await yieldLoop();await waitResume(id);}clockMs=columns.closeTime[index];candles=[];for(var row=Math.max(0,index-WINDOW_BARS+1);row<=index;row++)candles.push({time:columns.openTime[row],open:columns.open[row],high:columns.high[row],low:columns.low[row],close:columns.close[row],volume:columns.volume[row],closeTime:columns.closeTime[row]});var c=candles[candles.length-1];currentPrice=c.close;
        var execution=window.HNDTradeEngine.evaluate({symbol:message.context.symbol,interval:message.context.interval,price:null,candles:candles,setupState:prevSetup,tradePlanState:prevPlan});collectTerminal(execution,collector);var pn=stateName(prevTrade,"NO_TRADE"),en=stateName(execution,"NO_TRADE");if(pn!==en){var t=execution.activeTrade||execution.lastClosedTrade||{};tradeEvents.push(transition("TRADE",index,columns,pn,en,{phase:"EXECUTION",tradeId:t.id??null,planKey:t.planKey??null,direction:t.direction??null,entryPrice:finite(t.entryPrice),stopLoss:finite(t.stopLoss),takeProfit:finite(t.takeProfit),exitPrice:finite(t.exitPrice),realizedR:finite(t.realizedR),reason:t.exitReason??execution.lastEvaluation?.debug?.primaryReason??null}));}
        var structure=detectStructureEvents({lookback:3,limit:profile.structureHistoryLimit,includeBOS:true,includeCHoCH:true}),liquidity=detectLiquidityZones({lookback:3,tolerance:0.0015,minTouches:2,limit:20,includeSwept:true,includeBroken:false}),strongest=getStrongestLiquidityZones(liquidity),obs=detectOrderBlocks({limit:profile.rawZoneHistoryLimit,includeInvalidated:true}),fvgs=detectFVGs({limit:profile.rawZoneHistoryLimit,includeInvalidated:true}),qualified=selectStructureConfirmedPriceZones({candles:candles,structureEvents:structure,orderBlocks:obs,fvgs:fvgs},copy(profile.structureQualificationOptions)),analysis=analyzeMarket();
        var setup=window.HNDSetupEngine.evaluate({symbol:message.context.symbol,interval:message.context.interval,candles:candles,price:c.close,analysis:analysis,qualifiedPriceZones:qualified,mtfState:null}),ps=stateName(prevSetup,"NO_SETUP"),ns=stateName(setup,"NO_SETUP");if(ns!==ps||prevSetup.currentSetup?.key!==setup.currentSetup?.key){var s=setup.currentSetup||setup.lastTerminalSetup||{};setupEvents.push(transition("SETUP",index,columns,ps,ns,{key:s.key??null,direction:s.direction??null,sourceType:s.sourceType??null,entryTarget:finite(s.entryTarget),quality:finite(s.quality),reason:s.reason??setup.lastEvaluation?.debug?.primaryReason??null}));}
        var plan=window.HNDTradePlanEngine.evaluate({symbol:message.context.symbol,interval:message.context.interval,price:c.close,candles:candles,setupState:setup,liquidityZones:liquidity,strongestLiquidity:strongest}),pp=stateName(prevPlan,"NO_PLAN"),np=stateName(plan,"NO_PLAN");if(np!==pp||prevPlan.currentPlan?.key!==plan.currentPlan?.key){var p=plan.currentPlan||plan.lastTerminalPlan||{};planEvents.push(transition("PLAN",index,columns,pp,np,{planKey:p.key??null,setupKey:p.setupKey??null,direction:p.direction??null,entryPrice:finite(p.entryPrice),stopLoss:finite(p.stopLoss),takeProfit:finite(p.takeProfit),riskReward:finite(p.riskReward),targetSource:p.targetSource??null,reason:p.reason??plan.lastEvaluation?.debug?.primaryReason??null}));}
        var sync=window.HNDTradeEngine.evaluate({symbol:message.context.symbol,interval:message.context.interval,price:null,candles:candles,setupState:setup,tradePlanState:plan});collectTerminal(sync,collector);var sn=stateName(sync,"NO_TRADE"),ep=execution.pendingExecution?.planKey??null,sp=sync.pendingExecution?.planKey??null;if(sn!==en||ep!==sp){var st=sync.activeTrade||sync.lastClosedTrade||{},pl=plan.currentPlan||{};tradeEvents.push(transition("TRADE",index,columns,en,sn,{phase:"END_OF_CANDLE_SYNC",tradeId:st.id??null,planKey:sp??pl.key??null,direction:st.direction??pl.direction??null,entryPrice:finite(st.entryPrice??pl.entryPrice),stopLoss:finite(st.stopLoss??pl.stopLoss),takeProfit:finite(st.takeProfit??pl.takeProfit),exitPrice:finite(st.exitPrice),realizedR:finite(st.realizedR),reason:sync.lastEvaluation?.debug?.primaryReason??null}));}
        prevSetup=copy(setup);prevPlan=copy(plan);prevTrade=copy(sync);evaluated++;if(evaluated%CHECKPOINT_BARS===0){var cp={candleIndex:index,candleTime:c.time,signal:analysis?.signal??null,bullScore:finite(analysis?.bullScore),bearScore:finite(analysis?.bearScore),confidence:finite(analysis?.confidence),structureEventCount:structure.length,liquidityZoneCount:liquidity.length,qualifiedOBCount:qualified?.orderBlocks?.length||0,qualifiedFVGCount:qualified?.fvgs?.length||0,setupState:ns,setupKey:setup.currentSetup?.key??null,planState:np,planKey:plan.currentPlan?.key??null,tradeState:sn,activeTradeId:sync.activeTrade?.id??null,closedTradeCount:collector.total};cp.checkpointChecksum=hash(cp);checkpoints.push(cp);}if(evaluated%CHUNK_BARS===0)post("PROGRESS",id,{repetition:repetition,processedBars:evaluated,totalBars:count-499,progressPercent:((repetition-1)*(count-499)+evaluated)/(2*(count-499))*100});
    }
    var finalStates={setup:window.HNDSetupEngine.getState(),plan:window.HNDTradePlanEngine.getState(),trade:window.HNDTradeEngine.getState()};collectTerminal(finalStates.trade,collector);var trades=collector.trades.map(function(t){return normalizeTrade(t,map);}),closed=collector.tp+collector.sl,summary={totalSetupTransitions:setupEvents.length,totalPlanTransitions:planEvents.length,totalTradeTransitions:tradeEvents.length,tpCount:collector.tp,slCount:collector.sl,cancelledTradeCount:collector.cancelled,totalTerminalTrades:collector.total,closedTrades:closed,diagnosticNetR:collector.netR,diagnosticWinRate:closed?collector.tp/closed*100:null,openTradeAtEnd:Boolean(finalStates.trade.activeTrade),pendingPlanAtEnd:finalStates.plan.status==="READY"?copy(finalStates.plan.currentPlan):null,datasetChecksum:message.datasetMetadata.selectedChecksum};var normalized={setupEvents:sanitize(setupEvents),planEvents:sanitize(planEvents),tradeEvents:sanitize(tradeEvents),checkpoints:sanitize(checkpoints),trades:sanitize(trades),summary:sanitize(summary),finalStates:sanitize(finalStates)};var digest=hash(normalized);post("REPETITION_COMPLETED",id,{repetition:repetition,parityDigest:digest});return{normalized:normalized,parityDigest:digest};
}
function normalizeExpected(r){var s=r.summary||{};return{setupEvents:sanitize(r.setupEvents||[]),planEvents:sanitize(r.planEvents||[]),tradeEvents:sanitize(r.tradeEvents||[]),checkpoints:sanitize(r.checkpoints||[]),trades:sanitize(r.trades||[]),summary:sanitize({totalSetupTransitions:s.totalSetupTransitions,totalPlanTransitions:s.totalPlanTransitions,totalTradeTransitions:(r.tradeEvents||[]).length,tpCount:s.tpCount,slCount:s.slCount,cancelledTradeCount:s.cancelledTradeCount,totalTerminalTrades:s.totalTerminalTrades,closedTrades:s.closedTrades,diagnosticNetR:s.diagnosticNetR,diagnosticWinRate:s.diagnosticWinRate,openTradeAtEnd:s.openTradeAtEnd,pendingPlanAtEnd:s.pendingPlanAtEnd,datasetChecksum:s.datasetChecksum}),finalStates:sanitize(r.finalStates)};}
async function validateHistorical(message){control={requestId:message.requestId,paused:false,cancelled:false,resume:null};forbiddenNetworkCallCount=0;try{if(message.rulesetFingerprint!==HND_PARITY_RULESET_FINGERPRINT)throw new Error("RULESET_FINGERPRINT_MISMATCH");var locked=message.validationSnapshot||{},metadata=message.datasetMetadata||{},config=message.config||{},context=message.context||{};if(locked.requestId!==message.requestId||locked.symbol!==context.symbol||locked.interval!==context.interval||locked.selectedCandleCount!==config.selectedCandleCount||locked.selectedChecksum!==metadata.selectedChecksum||locked.originalDatasetId!==metadata.originalDatasetId||locked.originalCandleCount!==metadata.originalCandleCount||locked.profileVersion!==HND_PARITY_PROFILE_VERSION||locked.rulesetFingerprint!==HND_PARITY_RULESET_FINGERPRINT)throw new Error("VALIDATION_SNAPSHOT_MISMATCH");post("PREFLIGHT_PASSED",message.requestId);var a=await referenceRun(message,1),b=await referenceRun(message,2),deterministic=a.parityDigest===b.parityDigest;var expected=normalizeExpected(message.expectedReplayResult),details=[],total={count:0};compare(expected,a.normalized,"HISTORICAL","",details,total);var result={status:deterministic&&total.count===0?"HISTORICAL_STATEFUL_PARITY_PASS":"HISTORICAL_STATEFUL_PARITY_FAIL",symbol:locked.symbol,interval:locked.interval,selectedCandleCount:locked.selectedCandleCount,selectedChecksum:locked.selectedChecksum,originalDatasetId:locked.originalDatasetId,originalCandleCount:locked.originalCandleCount,replayEventChecksum:locked.replayEventChecksum,profileVersion:HND_PARITY_PROFILE_VERSION,rulesetFingerprint:HND_PARITY_RULESET_FINGERPRINT,referenceDeterministic:deterministic,referenceDigests:[a.parityDigest,b.parityDigest],parityDigest:a.parityDigest,mismatchCount:total.count,mismatches:details,expectedDigest:hash(expected),summary:a.normalized.summary,counts:{setup:a.normalized.setupEvents.length,plan:a.normalized.planEvents.length,trade:a.normalized.tradeEvents.length,checkpoints:a.normalized.checkpoints.length,terminal:a.normalized.trades.length},finalStates:a.normalized.finalStates,forbiddenNetworkCallCount:forbiddenNetworkCallCount};post("HISTORICAL_PARITY_COMPLETED",message.requestId,{result:result});}catch(error){if(error.name==="AbortError")post("CANCELLED",message.requestId);else post("ERROR",message.requestId,{reason:String(error.message||error),error:{name:error.name||"Error",message:String(error.message||error).slice(0,300)}});}}
self.onmessage=function(event){var m=event.data||{};if(m.type==="VALIDATE_LIVE_STATELESS"){forbiddenNetworkCallCount=0;try{validateLive(m);}catch(error){post("ERROR",m.requestId,{reason:String(error.message||error),error:{name:error.name||"Error",message:String(error.message||error).slice(0,300)}});}return;}if(m.type==="VALIDATE_HISTORICAL_STATEFUL"){validateHistorical(m);return;}if(m.requestId!==control.requestId)return;if(m.type==="PAUSE")control.paused=true;if(m.type==="RESUME"){control.paused=false;var r=control.resume;control.resume=null;r?.();}if(m.type==="CANCEL"){control.cancelled=true;control.paused=false;var c=control.resume;control.resume=null;c?.();}};
post("READY",null);
