"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path");
const swing=require("../../js/hndai-v1/swingDetector.js");const tests=[];function test(n,f){tests.push({n,f});}
function c(i,h,l,o){return Object.assign({openTime:i*1000,closeTime:i*1000+999,open:(h+l)/2,high:h,low:l,close:(h+l)/2,volume:10},o);}
function run(a,o){return swing.detectSwings(a,Object.assign({nowMs:999999},o));}
const peak=[c(0,2,0),c(1,3,-1),c(2,10,-5),c(3,4,-2),c(4,3,-1)];
test("defaults correct",()=>assert.deepStrictEqual(swing.getDefaults(),{leftBars:2,rightBars:2}));
test("defaults new",()=>assert.notStrictEqual(swing.getDefaults(),swing.getDefaults()));
test("invalid nowMs",()=>assert.strictEqual(swing.detectSwings([],{}).error,"INVALID_NOW_MS"));
test("nowMs priority",()=>assert.strictEqual(swing.detectSwings(null,{leftBars:0}).error,"INVALID_NOW_MS"));
test("default window",()=>assert.deepStrictEqual(run([]).config,{leftBars:2,rightBars:2}));
test("custom window",()=>assert.deepStrictEqual(run([],{leftBars:1,rightBars:3}).config,{leftBars:1,rightBars:3}));
[[0,2],[2,0],["1",2],[1.5,2],[2,"1"],[2,1.5]].forEach((x,i)=>test("invalid window "+i,()=>assert.strictEqual(run([], {leftBars:x[0],rightBars:x[1]}).error,"INVALID_WINDOW")));
test("nonarray",()=>assert.strictEqual(run(null).error,"INVALID_CANDLE_SERIES"));
test("empty valid",()=>assert.ok(run([]).valid&&!run([]).ready));
test("canonical accepted",()=>assert.strictEqual(run([c(0,2,0)]).valid,true));
test("kline accepted",()=>assert.strictEqual(run([[0,1,2,0,1,10,999]]).valid,true));
test("invalid candle rejects all",()=>assert.strictEqual(run([null]).error,"INVALID_CANDLE_SERIES"));
test("rejected reason",()=>assert.strictEqual(run([null]).rejected[0].reason,"INVALID_INPUT"));
test("rejected index",()=>assert.strictEqual(run([c(0,2,0),null]).rejected[0].inputIndex,1));
test("duplicate last valid",()=>assert.strictEqual(run([c(0,2,0),c(0,9,-1),c(1,2,0),c(2,3,-1)],{leftBars:1,rightBars:1}).duplicateOpenTimeCount,1));
test("raw order sorted",()=>assert.deepStrictEqual(run([c(2,2,0),c(0,2,0),c(1,2,0)]).openTimes,[0,1000,2000]));
test("source count",()=>assert.strictEqual(run(peak).sourceCandleCount,5));
test("closed count",()=>assert.strictEqual(run(peak,{nowMs:3999}).closedCandleCount,4));
test("excluded count",()=>assert.strictEqual(run(peak,{nowMs:3999}).excludedOpenCandleCount,1));
test("open excluded",()=>assert.strictEqual(run(peak,{nowMs:3999}).openTimes.length,4));
test("raw isClosed ignored",()=>assert.strictEqual(run([c(0,2,0,{isClosed:true})],{nowMs:0}).closedCandleCount,0));
test("warmup false",()=>assert.strictEqual(run(peak.slice(0,4)).ready,false));
test("minimum ready",()=>assert.strictEqual(run(peak).ready,true));
test("candidate count",()=>assert.strictEqual(run(peak).evaluatedCandidateCount,1));
test("simple high",()=>assert.strictEqual(run(peak).swingHighs.length,1));
test("simple low",()=>assert.strictEqual(run(peak).swingLows.length,1));
test("strict high",()=>assert.strictEqual(run(peak).swingHighs[0].price,10));
test("strict low",()=>assert.strictEqual(run(peak).swingLows[0].price,-5));
test("equal high no swing",()=>assert.strictEqual(run([c(0,2,0),c(1,3,0),c(2,5,0),c(3,5,0),c(4,2,0)]).swingHighs.length,0));
test("equal low no swing",()=>assert.strictEqual(run([c(0,2,0),c(1,3,-5),c(2,5,-5),c(3,4,0),c(4,2,0)]).swingLows.length,0));
test("candidate index",()=>assert.strictEqual(run(peak).events[0].candidateIndex,2));
test("confirmed index",()=>assert.strictEqual(run(peak).events[0].confirmedAtIndex,4));
test("confirmed open time",()=>assert.strictEqual(run(peak).events[0].confirmedAtOpenTime,4000));
test("confirmed close time",()=>assert.strictEqual(run(peak).events[0].confirmedAtCloseTime,4999));
test("not before right bars",()=>assert.strictEqual(run(peak.slice(0,4)).events.length,0));
test("appears with right bars",()=>assert.strictEqual(run(peak).events.length,2));
test("same candle two events",()=>assert.strictEqual(run(peak).events.length,2));
test("high before low",()=>assert.deepStrictEqual(run(peak).events.map(x=>x.type),["SWING_HIGH","SWING_LOW"]));
test("event ordering",()=>assert.ok(run(peak).events[0].confirmedAtIndex<=run(peak).events[1].confirmedAtIndex));
test("high filter",()=>assert.ok(run(peak).swingHighs.every(x=>x.type==="SWING_HIGH")));
test("low filter",()=>assert.ok(run(peak).swingLows.every(x=>x.type==="SWING_LOW")));
test("latest high",()=>assert.strictEqual(run(peak).latestHigh.type,"SWING_HIGH"));
test("latest low",()=>assert.strictEqual(run(peak).latestLow.type,"SWING_LOW"));
test("latest null",()=>assert.strictEqual(run([]).latestHigh,null));
test("event schema",()=>assert.deepStrictEqual(Object.keys(run(peak).events[0]),["type","candidateIndex","openTime","closeTime","price","confirmedAtIndex","confirmedAtOpenTime","confirmedAtCloseTime"]));
test("public API",()=>assert.deepStrictEqual(Object.keys(swing).sort(),["detectSwings","getDefaults"]));
test("normalizer calls present",()=>{const s=fs.readFileSync(path.join(__dirname,"../../js/hndai-v1/swingDetector.js"),"utf8");assert.ok(s.includes("normalizer.normalizeCandles")&&s.includes("normalizer.validateCandleSequence"));});
test("input immutable",()=>{const a=peak.map(x=>Object.assign({},x)),s=JSON.stringify(a);run(a);assert.strictEqual(JSON.stringify(a),s);});
test("options immutable",()=>{const o={nowMs:9999,leftBars:2,rightBars:2},s=JSON.stringify(o);swing.detectSwings(peak,o);assert.strictEqual(JSON.stringify(o),s);});
test("output isolation",()=>{const a=run(peak);a.events[0].price=0;a.openTimes[0]=9;assert.strictEqual(run(peak).events[0].price,10);});
test("array clones",()=>assert.notStrictEqual(run(peak).events,run(peak).events));
test("event clones across arrays",()=>assert.notStrictEqual(run(peak).events[0],run(peak).swingHighs[0]));
test("latest clone",()=>{const r=run(peak);assert.notStrictEqual(r.latestHigh,r.swingHighs[0]);});
test("determinism",()=>assert.deepStrictEqual(run(peak),run(peak)));
test("numeric strings",()=>assert.strictEqual(run([[0,"1","2","0","1","10",999]]).valid,true));
test("one one window",()=>assert.strictEqual(run([c(0,2,0),c(1,5,-2),c(2,2,0)],{leftBars:1,rightBars:1}).events.length,2));
test("asymmetric window",()=>assert.strictEqual(run(peak.concat([c(5,2,0)]),{leftBars:2,rightBars:3}).ready,true));
test("ready no swings",()=>assert.ok(run([c(0,2,0),c(1,3,1),c(2,4,2),c(3,5,3),c(4,6,4)]).ready));
test("openTimes closed only",()=>assert.deepStrictEqual(run(peak,{nowMs:2999}).openTimes,[0,1000,2000]));
test("rejected clone",()=>assert.notStrictEqual(run([null]).rejected,run([null]).rejected));
const wave=Array.from({length:100},(_,i)=>c(i,10+Math.sin(i/3)*5,5+Math.sin(i/3)*5));
test("100 candle causality",()=>{const a=run(wave.slice(0,99)).events,b=run(wave).events;assert.deepStrictEqual(b.slice(0,a.length),a);});
test("future append preserves confirmed",()=>{const a=run(peak).events,b=run(peak.concat([c(5,2,0)])).events;assert.deepStrictEqual(b.slice(0,a.length),a);});
for(let i=0;i<8;i++)test("window readiness variant "+i,()=>assert.strictEqual(run(peak.slice(0,i%5),{leftBars:1,rightBars:1}).ready,(i%5)>=3));
let p=0;for(const t of tests){try{t.f();p++;console.log(`PASS:${t.n}`);}catch(e){console.error(`HND_SWING_DETECTOR_TEST_FAILED:${t.n}`);console.error(e.stack||e);process.exitCode=1;break;}}if(p===tests.length)console.log(`HND_SWING_DETECTOR_TESTS_PASS:${tests.length}`);
