"use strict";
const assert = require("assert"), collection = require("../../js/hndai-v1/structureHistoricalRrCapEvidenceCollection.js"),
    api = require("../../js/hndai-v1/structureHistoricalRrCapEvidenceCollectionController.js"), tests = [];
function test(name, fn) { tests.push({ name, fn }); }
function config(change = {}) { const value = collection.getDefaultConfig(); Object.assign(value, { evaluationCandlesPerUnit:1, maximumUnitsPerCell:1, maximumCollectionUnits:12, sessionUnitLimit:1, unitCooldownMs:1000 }, change); return value; }
function candles(options, mutate) { const step = options.interval === "15m" ? 900000 : 14400000, first = options.evaluationCutoffTime - (options.candleCount - 1) * step;
    const rows = Array.from({length:options.candleCount}, (_, index) => { const closeTime = first + index * step; return {openTime:closeTime-step+1,closeTime,open:100,high:101,low:99,close:100,volume:1}; });
    if (mutate) mutate(rows, step); return rows; }
function dependencies(change = {}) { const calls = [], schemas = { pager:"HND_STRUCTURE_HISTORICAL_REPLAY_BINANCE_PAGER_V1", replay:"HND_STRUCTURE_HISTORICAL_SHADOW_REPLAY_V1", mismatch:"HND_STRUCTURE_HISTORICAL_MISMATCH_ANALYSIS_V1", outcome:"HND_STRUCTURE_HISTORICAL_MISMATCH_OUTCOME_V1", scenario:"HND_STRUCTURE_HISTORICAL_RR_CAP_SCENARIO_ANALYSIS_V1" };
    const deps = { collection,
        pager:{getSchemaVersion:()=>schemas.pager,fetchClosedCandles:async options=>{calls.push("pager");return {valid:true,schemaVersion:schemas.pager,candles:candles(options),pageCount:1};}},
        replay:{getSchemaVersion:()=>schemas.replay,getDefaultConfig:()=>({symbol:"BTCUSDT",interval:"15m",warmupCandles:250,maximumEvaluationCandles:1,includeNonComparable:true,evaluationCutoffTime:1}),runReplay:(rows,cfg)=>{calls.push("replay");return {valid:true,schemaVersion:schemas.replay,source:"HISTORICAL_REPLAY",countsTowardLiveReadiness:false,symbol:cfg.symbol,interval:cfg.interval,evaluationCutoffTime:cfg.evaluationCutoffTime,observations:[]};}},
        mismatch:{getSchemaVersion:()=>schemas.mismatch,analyzeReplay:()=>{calls.push("mismatch");return {valid:true,schemaVersion:schemas.mismatch,source:"HISTORICAL_REPLAY",countsTowardLiveReadiness:false,status:"NO_REVIEW_ITEMS",mismatchCount:0,reviewItems:[]};}},
        outcome:{getSchemaVersion:()=>schemas.outcome,getDefaultPolicy:()=>({maximumForwardBars:24,includeMatches:false}),analyzeOutcomes:()=>{calls.push("outcome");return {valid:true,schemaVersion:schemas.outcome,source:"HISTORICAL_REPLAY",countsTowardLiveReadiness:false,outcomeItems:[]};}},
        scenario:{getSchemaVersion:()=>schemas.scenario,getDefaultPolicy:()=>({maximumForwardBars:24,includeMatches:false}),analyzeScenarios:(m,r)=>{calls.push("scenario");const time=r.evaluationCutoffTime;return {valid:true,schemaVersion:schemas.scenario,source:"HISTORICAL_REPLAY",countsTowardLiveReadiness:false,scenarioItems:["ORIGINAL_UNCAPPED","MAX_2R","MAX_3R","MAX_4R","MAX_5R"].map((name,index)=>({key:"P1",candidateKey:"C1",symbol:r.symbol,interval:r.interval,evaluationCloseTime:time,scenario:name,direction:"LONG",entryPrice:100,stopLoss:90,originalTakeProfit:150,scenarioOutcome:"ENTRY_NOT_REACHED",originalOutcome:"ENTRY_NOT_REACHED",outcomeAt:null}))};}}
    }; Object.keys(change).forEach(key=>{ if (key in deps && typeof change[key] === "object") Object.assign(deps[key],change[key]); else deps[key]=change[key]; }); return {deps,calls}; }
test("exact API",()=>assert.deepStrictEqual(Object.keys(api).sort(),["getSchemaVersion","validateCandleGrid","createMemoryStore","createController"].sort()));
test("authoritative dependency order and atomic commit",async()=>{const fixture=dependencies(),store=api.createMemoryStore(),controller=api.createController({dependencies:fixture.deps,store,sleep:async()=>{}});await controller.create(config());const result=await controller.start();assert.deepStrictEqual(fixture.calls,["pager","replay","mismatch","outcome","scenario"]);assert.strictEqual(result.checkpoint.cursor,1);assert.strictEqual((await store.load()).cursor,1);});
test("exact grid accepts complete and rejects gap duplicate cutoff",()=>{const cp=collection.createManifest(config()),unit=collection.getNextWorkUnit(cp), options={interval:unit.interval,evaluationCutoffTime:unit.fetchEnd,candleCount:unit.expectedCandleCount};assert.strictEqual(api.validateCandleGrid(candles(options),unit).valid,true);
    assert.strictEqual(api.validateCandleGrid(candles(options,(r,s)=>r[5].closeTime+=s),unit).valid,false);assert.strictEqual(api.validateCandleGrid(candles(options,r=>{r[5].closeTime=r[4].closeTime;r[5].openTime=r[4].openTime;}),unit).error,"DUPLICATE_CANDLE");assert.strictEqual(api.validateCandleGrid(candles(options,r=>r.at(-1).closeTime+=1),unit).valid,false);});
test("network 429 timeout is bounded and never commits",async()=>{let attempts=0;const fixture=dependencies({pager:{fetchClosedCandles:async()=>{attempts+=1;return {valid:false,schemaVersion:"HND_STRUCTURE_HISTORICAL_REPLAY_BINANCE_PAGER_V1",error:"BINANCE_PAGINATION_FAILED",candles:[]};}}}),store=api.createMemoryStore(),controller=api.createController({dependencies:fixture.deps,store,sleep:async()=>{}});await controller.create(config());const before=(await store.load()).checkpointHash,result=await controller.start();assert.strictEqual(attempts,3);assert.strictEqual(result.state,"PAUSED_RETRYABLE");assert.strictEqual((await store.load()).checkpointHash,before);});
test("partial or duplicate segment never reaches replay",async()=>{const fixture=dependencies({pager:{fetchClosedCandles:async options=>({valid:true,schemaVersion:"HND_STRUCTURE_HISTORICAL_REPLAY_BINANCE_PAGER_V1",candles:candles(options,r=>r.pop())})}}),controller=api.createController({dependencies:fixture.deps,store:api.createMemoryStore()});await controller.create(config());const result=await controller.start();assert.strictEqual(result.state,"FAILED_CLOSED");assert.ok(!fixture.calls.includes("replay"));assert.strictEqual(result.checkpoint.cursor,0);});
test("transaction abort quota leaves in-memory and durable cursor unchanged",async()=>{const fixture=dependencies(),base=api.createMemoryStore(),store={load:base.load,clearRunning:async()=>{},commit:async cp=>{if(cp.cursor)throw new Error("QuotaExceededError");return base.commit(cp);}},controller=api.createController({dependencies:fixture.deps,store});await controller.create(config());const result=await controller.start();assert.strictEqual(result.state,"FAILED_CLOSED");assert.strictEqual(result.checkpoint.cursor,0);assert.strictEqual((await store.load()).cursor,0);});
test("pause waits for current unit then preserves completed checkpoint",async()=>{let release;const gate=new Promise(resolve=>release=resolve),fixture=dependencies(),original=fixture.deps.pager.fetchClosedCandles;fixture.deps.pager.fetchClosedCandles=async options=>{await gate;return original(options);};const controller=api.createController({dependencies:fixture.deps,store:api.createMemoryStore()});await controller.create(config({sessionUnitLimit:2}));const running=controller.start();controller.pause();release();const result=await running;assert.strictEqual(result.state,"PAUSED");assert.strictEqual(result.checkpoint.cursor,1);});
test("cancel discards current partial unit and completed checkpoint survives restore",async()=>{let release;const gate=new Promise(resolve=>release=resolve),fixture=dependencies(),original=fixture.deps.pager.fetchClosedCandles;fixture.deps.pager.fetchClosedCandles=async options=>{await gate;return original(options);};const store=api.createMemoryStore(),controller=api.createController({dependencies:fixture.deps,store});await controller.create(config());const running=controller.start();controller.cancelCurrentUnit();release();const result=await running;assert.strictEqual(result.checkpoint.cursor,0);const restored=api.createController({dependencies:fixture.deps,store});assert.strictEqual((await restored.restore()).checkpoint.cursor,0);});
test("source schema mismatch checkpoint/dependency fails closed",async()=>{const fixture=dependencies();fixture.deps.outcome.getSchemaVersion=()=>"UNKNOWN";const controller=api.createController({dependencies:fixture.deps,store:api.createMemoryStore()});const result=await controller.create(config());assert.strictEqual(result.state,"FAILED_CLOSED");assert.match(result.error,/DEPENDENCY_SCHEMA_MISMATCH/);});
test("crash resume repeats only uncommitted unit",async()=>{const fixture=dependencies(),store=api.createMemoryStore(),first=api.createController({dependencies:fixture.deps,store,sleep:async()=>{}});await first.create(config());await first.start();const callsAfter=fixture.calls.filter(x=>x==="pager").length,second=api.createController({dependencies:fixture.deps,store,sleep:async()=>{}});await second.restore();await second.start();assert.strictEqual(fixture.calls.filter(x=>x==="pager").length,callsAfter+1);assert.strictEqual(second.getSnapshot().checkpoint.cursor,2);});
test("bounded pilot accepts BTCUSDT 4h and auto-pauses after exactly one unit",async()=>{const fixture=dependencies(),store=api.createMemoryStore(),controller=api.createController({dependencies:fixture.deps,store,sleep:async()=>{}}),pilot={mode:"PILOT_ONLY",symbol:"BTCUSDT",interval:"4h",split:"EXPLORATORY",maximumCompletedUnits:1};
    const created=await controller.createPilot(pilot);assert.strictEqual(created.state,"PILOT_READY");assert.strictEqual(created.checkpoint.workUnit.interval,"4h");const result=await controller.startPilot();
    assert.strictEqual(result.state,"PILOT_COMPLETED_PAUSED");assert.strictEqual(result.checkpoint.cursor,1);assert.strictEqual(result.readiness,"NONE");assert.strictEqual(fixture.calls.filter(x=>x==="pager").length,1);});
test("completed pilot resume and reload never start a second unit",async()=>{const fixture=dependencies(),store=api.createMemoryStore(),first=api.createController({dependencies:fixture.deps,store,sleep:async()=>{}}),pilot={mode:"PILOT_ONLY",symbol:"ETHUSDT",interval:"15m",split:"EXPLORATORY",maximumCompletedUnits:1};
    await first.createPilot(pilot);await first.startPilot();const calls=fixture.calls.filter(x=>x==="pager").length;assert.strictEqual((await first.resumePilot()).state,"PILOT_COMPLETED_PAUSED");
    const second=api.createController({dependencies:fixture.deps,store,sleep:async()=>{}});assert.strictEqual((await second.restorePilot()).state,"PILOT_COMPLETED_PAUSED");assert.strictEqual((await second.resumePilot()).state,"PILOT_COMPLETED_PAUSED");assert.strictEqual(fixture.calls.filter(x=>x==="pager").length,calls);});
test("full and pilot stores fail closed on cross-restore",async()=>{const fixture=dependencies(),fullStore=api.createMemoryStore(),full=api.createController({dependencies:fixture.deps,store:fullStore});await full.create(config());
    assert.strictEqual((await api.createController({dependencies:fixture.deps,store:fullStore}).restorePilot()).state,"PILOT_FAILED_CLOSED");const pilotStore=api.createMemoryStore(),pilot=api.createController({dependencies:fixture.deps,store:pilotStore});await pilot.createPilot({mode:"PILOT_ONLY",symbol:"SOLUSDT",interval:"4h",split:"EXPLORATORY",maximumCompletedUnits:1});
    assert.strictEqual((await api.createController({dependencies:fixture.deps,store:pilotStore}).restore()).state,"FAILED_CLOSED");});
test("stale pilot completion after cancel cannot commit",async()=>{let release;const gate=new Promise(resolve=>release=resolve),fixture=dependencies(),original=fixture.deps.pager.fetchClosedCandles;fixture.deps.pager.fetchClosedCandles=async options=>{await gate;return original(options);};
    const store=api.createMemoryStore(),controller=api.createController({dependencies:fixture.deps,store});await controller.createPilot({mode:"PILOT_ONLY",symbol:"BTCUSDT",interval:"4h",split:"EXPLORATORY",maximumCompletedUnits:1});const running=controller.startPilot();controller.cancelPilotUnit();release();const result=await running;
    assert.strictEqual(result.state,"PILOT_PAUSED");assert.strictEqual((await store.load()).cursor,0);assert.strictEqual(controller.getPilotSnapshot().checkpoint.cursor,0);});
(async()=>{let passed=0;for(const item of tests){try{await item.fn();passed+=1;console.log("PASS:"+item.name);}catch(error){console.error("FAIL:"+item.name);console.error(error.stack);process.exitCode=1;break;}}if(passed===tests.length)console.log("HND_STRUCTURE_HISTORICAL_RR_CAP_EVIDENCE_COLLECTION_CONTROLLER_TESTS_PASS:"+passed);})();
