"use strict";
const assert = require("assert"), fs = require("fs"), path = require("path"), vm = require("vm");
const modulePath = path.resolve(__dirname, "../../js/hndai-v1/structureHistoricalLegacyCandidateAdapter.js");
const api = require(modulePath), tests = []; function test(name, fn) { tests.push({ name, fn }); }
function candle(i, close, high, low) { return { openTime: i * 1000, closeTime: i * 1000 + 999,
    open: close, high, low, close, volume: 10 }; }
const real = [candle(1, 5, 6, 4), candle(2, 6, 7, 4), candle(3, 10, 12, 3),
    candle(4, 6, 7, 4), candle(5, 7, 8, 5), candle(6, 13, 14, 12)];
const config = { symbol: "BTCUSDT", interval: "15m", warmupCandles: 1,
    maximumEvaluationCandles: 10, includeNonComparable: true, evaluationCutoffTime: real.at(-1).closeTime };
test("CommonJS API exact", () => assert.deepStrictEqual(Object.keys(api).sort(), ["getSchemaVersion", "evaluateHistoricalShadow"].sort()));
test("schema exact", () => assert.strictEqual(api.getSchemaVersion(), "HND_STRUCTURE_HISTORICAL_LEGACY_CANDIDATE_ADAPTER_V1"));
test("insufficient real legacy warmup is not comparable", () => { let lifecycle; let result; real.forEach((_,i)=>{result=api.evaluateHistoricalShadow(real.slice(0,i+1),config,real[i].closeTime,lifecycle);lifecycle=result.lifecycle;}); assert.deepStrictEqual([result.comparison,result.reason,result.legacyDecision],["NOT_COMPARABLE","INSUFFICIENT_WARMUP",null]); });
test("candidate is created only on exact confirmation candle", () => { let lifecycle; let created=[]; real.forEach((_,i)=>{const r=api.evaluateHistoricalShadow(real.slice(0,i+1),config,real[i].closeTime,lifecycle);lifecycle=r.lifecycle;created.push(r.pendingCandidateCreatedCount);});assert.deepStrictEqual(created,[0,0,0,0,2,0]); });
test("resolved event is not compared twice", () => { let lifecycle; real.forEach((_,i)=>{const r=api.evaluateHistoricalShadow(real.slice(0,i+1),config,real[i].closeTime,lifecycle);lifecycle=r.lifecycle;});const extended=real.concat([{...real.at(-1),openTime:7000,closeTime:7999}]);const r=api.evaluateHistoricalShadow(extended,config,extended.at(-1).closeTime,lifecycle);assert.deepStrictEqual([r.comparisons.length,r.pendingCandidateResolvedCount],[0,0]);});
test("real candidate is not fabricated without event", () => assert.strictEqual(api.evaluateHistoricalShadow(real.slice(0, 3), config, real[2].closeTime).comparison, "NOT_COMPARABLE"));
test("prefix only reaches pipeline", () => { let seen=0;const pipeline=require("../../js/hndai-v1/structurePipelineOrchestrator.js"),original=pipeline.analyzeStructure;pipeline.analyzeStructure=(prefix,...rest)=>{seen=prefix.length;return original(prefix,...rest);};api.evaluateHistoricalShadow(real.slice(0,4),config,real[3].closeTime);pipeline.analyzeStructure=original;assert.strictEqual(seen,4);});
test("invalid input fails closed", () => assert.strictEqual(api.evaluateHistoricalShadow(null,config,1).valid,false));
function withLegacy(evaluator){const window={HNDStructurePipelineOrchestrator:require("../../js/hndai-v1/structurePipelineOrchestrator.js"),HNDStructureSetupAdapter:require("../../js/hndai-v1/structureSetupAdapter.js"),HNDSwingDetector:require("../../js/hndai-v1/swingDetector.js"),HNDStructurePendingCandidateContract:require("../../js/hndai-v1/structurePendingCandidateContract.js"),HNDHistoricalLegacySetupEvaluator:evaluator};vm.runInNewContext(fs.readFileSync(modulePath,"utf8"),{window,JSON,Object,Array,Number,Error,Set});return window.HNDStructureHistoricalLegacyCandidateAdapter;}
function runWith(evaluator){const x=withLegacy(evaluator);let lifecycle,result;real.forEach((_,i)=>{result=x.evaluateHistoricalShadow(real.slice(0,i+1),config,real[i].closeTime,lifecycle);lifecycle=result.lifecycle;});return result;}
test("verified legacy BLOCK creates real match",()=>{const r=runWith({evaluateHistoricalLegacy(prefix){return{valid:true,decision:"BLOCK",decisionSource:"FIXTURE_REAL_LEGACY_FILTER",reason:"WAIT_SIGNAL",candidateKey:null,evidence:{filter:"closeBelow20",close:prefix.at(-1).close}};}});assert.deepStrictEqual([r.comparison,r.legacyDecision,r.gateDecision],["MATCH_BLOCK","BLOCK","BLOCK"]);});
test("legacy filter change changes historical decision",()=>{const blocked=runWith({evaluateHistoricalLegacy(prefix){const allow=prefix.at(-1).close>=20;return{valid:true,decision:allow?"ALLOW":"BLOCK",decisionSource:"FIXTURE_REAL_LEGACY_FILTER",reason:allow?"SETUP_CREATED":"WAIT_SIGNAL",candidateKey:allow?"C":null,evidence:{minimumClose:20,close:prefix.at(-1).close}};}}),allowed=runWith({evaluateHistoricalLegacy(prefix){const allow=prefix.at(-1).close>=10;return{valid:true,decision:allow?"ALLOW":"BLOCK",decisionSource:"FIXTURE_REAL_LEGACY_FILTER",reason:allow?"SETUP_CREATED":"WAIT_SIGNAL",candidateKey:allow?"C":null,evidence:{minimumClose:10,close:prefix.at(-1).close}};}});assert.deepStrictEqual([blocked.legacyDecision,allowed.legacyDecision],["BLOCK","ALLOW"]);});
test("decision sources and evidence explicit",()=>{const r=runWith({evaluateHistoricalLegacy(){return{valid:true,decision:"ALLOW",decisionSource:"FIXTURE_REAL_LEGACY_FILTER",reason:"SETUP_CREATED",candidateKey:"C",evidence:{acceptedCandidates:1}};}});assert.deepStrictEqual([r.legacyDecisionSource,r.gateDecisionSource,r.legacyDecisionEvidence.acceptedCandidates],["FIXTURE_REAL_LEGACY_FILTER","HND_STRUCTURE_SETUP_ADAPTER_V1",1]);});
test("direct legacy and gate reasons projected",()=>{const r=runWith({evaluateHistoricalLegacy(){return{valid:true,decision:"ALLOW",decisionSource:"FIXTURE_REAL_LEGACY_FILTER",reason:"SETUP_CREATED",candidateKey:"C",evidence:{acceptedCandidates:1}};}});assert.deepStrictEqual([r.legacyReason,r.gateReason],["SETUP_CREATED",r.gateDecisionEvidence.reason]);});
test("malformed legacy evaluator not comparable",()=>{const r=runWith({evaluateHistoricalLegacy(){return{valid:true,decision:"ALLOW"};}});assert.deepStrictEqual([r.comparison,r.reason],["NOT_COMPARABLE","LEGACY_EVALUATOR_MALFORMED"]);});
test("legacy evaluator exception not comparable",()=>{const r=runWith({evaluateHistoricalLegacy(){throw Error("x");}});assert.strictEqual(r.reason,"LEGACY_EVALUATOR_EXCEPTION");});
test("no hardcoded legacy decision",()=>{const source=fs.readFileSync(modulePath,"utf8");assert.ok(!/legacyDecision:\s*["'](?:ALLOW|BLOCK)["']/.test(source));});
test("input not mutated", () => { const before = JSON.stringify(real); api.evaluateHistoricalShadow(real, config, real.at(-1).closeTime); assert.strictEqual(JSON.stringify(real), before); });
test("no live state writers", () => assert.ok(!/(Collection|Telemetry|Readiness|SetupEngine|TradeEngine|localStorage|fetch\()/.test(fs.readFileSync(modulePath, "utf8"))));
(async()=>{let n=0;for(const t of tests){try{await t.fn();n++;}catch(e){console.error(`FAIL: ${t.name}`);throw e;}}console.log(`Historical Legacy Candidate Adapter tests passed: ${tests.length} scenarios, ${n} assertions.`);})().catch(e=>{console.error(e);process.exitCode=1;});
