"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const modulePath=path.resolve(__dirname,"../../js/hndai-v1/structureHistoricalReplayBinancePager.js"),tests=[];function test(n,f){tests.push({name:n,fn:f});}
function candle(i){return{openTime:1000+i*900000,closeTime:1000+(i+1)*900000-1,open:100,high:101,low:99,close:100,volume:1};}
function load(rows, mutate){let calls=[];const api={async fetchHistoricalKlinesPage(params){calls.push({...params});let page=rows.filter(x=>x.closeTime<=params.endTime).slice(-params.limit).map(x=>JSON.parse(JSON.stringify(x)));return mutate?mutate(page,calls.length):page;}};const window={HNDAPI:api};vm.runInNewContext(fs.readFileSync(modulePath,"utf8"),{window,JSON,Object,Array,Number,Math,Map,Promise,setTimeout});return{api:window.HNDStructureHistoricalReplayBinancePager,calls};}
function options(change={}){return Object.assign({symbol:"BTCUSDT",interval:"15m",candleCount:251,evaluationCutoffTime:candle(399).closeTime,pageSize:100,requestDelayMs:100},change);}
test("browser API exact",()=>assert.deepStrictEqual(Object.keys(load([]).api).sort(),["getSchemaVersion","fetchClosedCandles"].sort()));
test("schema exact",()=>assert.strictEqual(load([]).api.getSchemaVersion(),"HND_STRUCTURE_HISTORICAL_REPLAY_BINANCE_PAGER_V1"));
test("invalid exact options fail closed",async()=>assert.strictEqual((await load([]).api.fetchClosedCandles({...options(),extra:1})).valid,false));
test("pagination exceeds 1000",async()=>{const rows=Array.from({length:2200},(_,i)=>candle(i)),x=load(rows),r=await x.api.fetchClosedCandles(options({candleCount:2001,evaluationCutoffTime:rows.at(-1).closeTime,pageSize:1000}));assert.ok(r.valid&&r.candles.length===2001&&r.pageCount===3);});
test("pages move backward",async()=>{const rows=Array.from({length:400},(_,i)=>candle(i)),x=load(rows);await x.api.fetchClosedCandles(options());assert.ok(x.calls.every((c,i)=>i===0||c.endTime<x.calls[i-1].endTime));});
test("duplicate closeTime deduplicated",async()=>{const rows=Array.from({length:400},(_,i)=>candle(i)),x=load(rows,(p,n)=>n===1?p.concat([p[0]]):p),r=await x.api.fetchClosedCandles(options());assert.ok(r.duplicateCount===1&&new Set(r.candles.map(x=>x.closeTime)).size===r.candles.length);});
test("cutoff enforced",async()=>{const rows=Array.from({length:400},(_,i)=>candle(i)),cutoff=rows[300].closeTime,r=await load(rows).api.fetchClosedCandles(options({evaluationCutoffTime:cutoff}));assert.ok(r.candles.every(x=>x.closeTime<=cutoff));});
test("network failure fail closed",async()=>{const window={HNDAPI:{async fetchHistoricalKlinesPage(){throw Error("x");}}};vm.runInNewContext(fs.readFileSync(modulePath,"utf8"),{window,JSON,Object,Array,Number,Math,Map,Promise,setTimeout});assert.strictEqual((await window.HNDStructureHistoricalReplayBinancePager.fetchClosedCandles(options())).error,"BINANCE_PAGINATION_FAILED");});
test("repeated page stops on no unique progress",async()=>{const rows=Array.from({length:400},(_,i)=>candle(i));let fixed=null;const x=load(rows,(p)=>{if(!fixed)fixed=p;return fixed;});const r=await x.api.fetchClosedCandles(options());assert.ok(r.valid&&r.pageCount===2&&x.calls.length===2);});
test("malformed candle fails closed",async()=>{const rows=Array.from({length:300},(_,i)=>candle(i)),x=load(rows,(p)=>{p[0].high=1;return p;});assert.strictEqual((await x.api.fetchClosedCandles(options())).error,"BINANCE_PAGINATION_FAILED");});
test("429 retry is bounded",async()=>{let n=0;const window={HNDAPI:{async fetchHistoricalKlinesPage(){n++;const e=Error("rate");e.status=429;e.retryAfterMs=1;throw e;}}};vm.runInNewContext(fs.readFileSync(modulePath,"utf8"),{window,JSON,Object,Array,Number,Math,Map,Promise,setTimeout});const r=await window.HNDStructureHistoricalReplayBinancePager.fetchClosedCandles(options({requestDelayMs:100}));assert.deepStrictEqual([r.valid,n],[false,3]);});
test("maximum page bound is deterministic",async()=>{const rows=Array.from({length:400},(_,i)=>candle(i)),r=await load(rows).api.fetchClosedCandles(options());assert.strictEqual(r.maximumPages,5);});
test("no raw response metadata",async()=>{const r=await load(Array.from({length:300},(_,i)=>candle(i))).api.fetchClosedCandles(options());assert.deepStrictEqual(Object.keys(r).sort(),["valid","error","schemaVersion","candles","pageCount","duplicateCount","maximumPages","rateLimitRetryCount"].sort());});
(async()=>{let n=0;for(const t of tests){try{await t.fn();n++;}catch(e){console.error(`FAIL: ${t.name}`);throw e;}}console.log(`Historical Replay Binance Pager tests passed: ${tests.length} scenarios, ${n} assertions.`);})().catch(e=>{console.error(e);process.exitCode=1;});
