"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm"),cp=require("child_process");
const root=path.resolve(__dirname,"../.."),sha="c8e70eae561ef2473b50204e177b83a871e06f08",cutoff=1705000000000;
function source(mode,file){return mode==="current"?fs.readFileSync(path.join(root,file),"utf8"):cp.execFileSync("git",["show",`${sha}:${file}`],{cwd:root,encoding:"utf8",maxBuffer:16*1024*1024});}
function runtime(mode){const FixedDate=class extends Date{static now(){return cutoff;}};const context={console:{log(){},warn(){},error(){}},Date:FixedDate,Math,JSON,Object,Array,Number,String,Boolean,Set,Map,Promise,Error,setTimeout,clearTimeout,setInterval,clearInterval,document:{querySelector(){return null;},addEventListener(){},removeEventListener(){},visibilityState:"visible"}};context.window=context;["js/api.js","js/indicators.js","js/smartmoney.js","js/strategy.js","js/mtf.js"].forEach(file=>vm.runInNewContext(source(mode,file),context,{filename:`${mode}:${file}`}));return context;}
const candles=Array.from({length:320},(_,i)=>{const time=1600000000000+i*900000,base=100+Math.sin(i/7)*8+i*0.025,close=base+Math.sin(i/3)*1.8;return{time,closeTime:time+899999,open:base,high:Math.max(base,close)+1.4,low:Math.min(base,close)-1.3,close,volume:100+Math.abs(Math.sin(i))*50};});
const current=runtime("current"),baseline=runtime("baseline");baseline.fixture=JSON.parse(JSON.stringify(candles));vm.runInNewContext("candles=fixture",baseline);
const options=current.getLiveStructureZoneQualificationOptions(),eventOptions={lookback:3,limit:100,includeBOS:true,includeCHoCH:true};
function snapshot(ctx,isCurrent){const analysis=isCurrent?ctx.analyzeMarket(candles):ctx.analyzeMarket();const events=ctx.detectStructureEvents(isCurrent?{...eventOptions,candles}:eventOptions),obs=ctx.detectOrderBlocks(isCurrent?{candles,limit:200,includeInvalidated:true}:{limit:200,includeInvalidated:true}),fvgs=ctx.detectFVGs(isCurrent?{candles,limit:200,includeInvalidated:true}:{limit:200,includeInvalidated:true}),zones=ctx.selectStructureConfirmedPriceZones({candles,structureEvents:events,orderBlocks:obs,fvgs},Object.assign({},options,{now:cutoff})),mtf=ctx.HNDMTFEngine.analyzeCandles(candles,"15m",cutoff);return{analysis,events,obs,fvgs,zones,mtf};}
const before=snapshot(baseline,false),after=snapshot(current,true),checks={signal:after.analysis.signal===before.analysis.signal,ema20:after.analysis.ema20===before.analysis.ema20,ema50:after.analysis.ema50===before.analysis.ema50,ema200:after.analysis.ema200===before.analysis.ema200,rsi:after.analysis.rsi===before.analysis.rsi,structureEvents:JSON.stringify(after.events)===JSON.stringify(before.events),orderBlocks:JSON.stringify(after.obs)===JSON.stringify(before.obs),fvgs:JSON.stringify(after.fvgs)===JSON.stringify(before.fvgs),qualifiedZones:JSON.stringify(after.zones)===JSON.stringify(before.zones),mtf:JSON.stringify(after.mtf)===JSON.stringify(before.mtf)};
assert.ok(Object.values(checks).every(Boolean),JSON.stringify(checks));console.log("PARITY="+JSON.stringify(checks));
