"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm");
const root=path.resolve(__dirname,"../.."),modulePath=path.join(root,"js/hndai-v1/structureHistoricalLegacyEvaluator.js"),api=require(modulePath),tests=[];
function test(name,fn){tests.push({name,fn});}
function candle(i){const open=100+i/10,close=open+0.1;return{openTime:1600000000000+i*900000,closeTime:1600000000000+(i+1)*900000-1,open,high:close+1,low:open-1,close,volume:10};}
const prefix=Array.from({length:200},(_,i)=>candle(i));
function context(change={}){return Object.assign({symbol:"BTCUSDT",interval:"15m",evaluationIndex:199,evaluationCloseTime:prefix[199].closeTime,pendingCandidate:{key:"PENDING"},consumedCandidateKeys:[],higherTimeframeCandles:[]},change);}
function zone(change={}){return Object.assign({id:"OB-1",kind:"ORDER_BLOCK",type:"BULLISH",status:"ACTIVE",structureQualified:true,structureSignificant:true,structureEventId:"EVENT-1",structureEventType:"BOS",structureConfirmationIndex:190,structureConfirmationTime:prefix[190].closeTime,startTime:prefix[180].openTime,confirmationTime:prefix[190].closeTime,high:120,low:118,structureSignificanceScore:100,structureATR:10,zoneHeightATR:0.2,dominantQualifiedZone:true,touches:0,qualificationVersion:"1"},change);}
function input(change={}){return Object.assign({symbol:"BTCUSDT",interval:"15m",price:119,candles:prefix.map(x=>({time:x.openTime,closeTime:x.closeTime,open:x.open,high:x.high,low:x.low,close:x.close,volume:x.volume})),analysis:{signal:"LONG",marketBias:"BULLISH"},qualifiedPriceZones:{orderBlocks:[zone()],fvgs:[]},mtfState:{rows:[]}},change);}
function load(builder,coreOverride){const window={HNDStructureHistoricalLegacyInputBuilder:builder};vm.runInNewContext(fs.readFileSync(path.join(root,"js/setupEngine.js"),"utf8"),{window,console,JSON,Object,Array,Number,Math,Date,Set,String,Boolean});if(coreOverride!==undefined)window.HNDSetupEngine=coreOverride;vm.runInNewContext(fs.readFileSync(modulePath,"utf8"),{window,JSON,Object,Array,Number,Math,Set,String});return window.HNDStructureHistoricalLegacyEvaluator;}
function builder(bundle=input()){return{buildHistoricalInput(){return{valid:true,status:"INPUT_READY",input:JSON.parse(JSON.stringify(bundle)),warnings:[]};}};}
test("CommonJS API",()=>assert.strictEqual(typeof api.evaluateHistoricalLegacy,"function"));
test("browser global API",()=>assert.strictEqual(load(builder()).getSchemaVersion(),api.getSchemaVersion()));
test("exact public API",()=>assert.deepStrictEqual(Object.keys(api).sort(),["getSchemaVersion","getVocabulary","evaluateHistoricalLegacy"].sort()));
test("schema exact",()=>assert.strictEqual(api.getSchemaVersion(),"HND_STRUCTURE_HISTORICAL_LEGACY_EVALUATOR_V1"));
test("vocabulary decisions",()=>assert.deepStrictEqual(api.getVocabulary().decisions,["ALLOW","BLOCK","UNAVAILABLE"]));
test("vocabulary cloned",()=>{const v=api.getVocabulary();v.decisions[0]="X";assert.strictEqual(api.getVocabulary().decisions[0],"ALLOW");});
for(const [name,change] of [["extra",{extra:1}],["symbol",{symbol:"btc"}],["interval",{interval:""}],["index",{evaluationIndex:198}],["cutoff",{evaluationCloseTime:0}],["pending",{pendingCandidate:null}],["consumed",{consumedCandidateKeys:null}],["htf",{higherTimeframeCandles:null}]])test("context exact "+name,()=>assert.strictEqual(load(builder()).evaluateHistoricalLegacy(prefix,context(change)).decision,"UNAVAILABLE"));
test("missing context field",()=>{const c=context();delete c.interval;assert.strictEqual(load(builder()).evaluateHistoricalLegacy(prefix,c).reason,"INVALID_HISTORICAL_INPUT");});
test("input not mutated",()=>{const p=JSON.parse(JSON.stringify(prefix)),c=context(),before=JSON.stringify([p,c]);load(builder()).evaluateHistoricalLegacy(p,c);assert.strictEqual(JSON.stringify([p,c]),before);});
test("deterministic",()=>{const x=load(builder());assert.deepStrictEqual(x.evaluateHistoricalLegacy(prefix,context()),x.evaluateHistoricalLegacy(prefix,context()));});
test("no Date.now",()=>assert.ok(!fs.readFileSync(modulePath,"utf8").includes("Date.now")));
test("no global candle state",()=>assert.ok(!/\b(window\.)?candles\b/.test(fs.readFileSync(modulePath,"utf8").replace(/higherTimeframeCandles/g,""))));
test("no live writers",()=>assert.ok(!/(localStorage|sessionStorage|cookie|TradeEngine|Readiness|Telemetry|Collection|fetch\()/.test(fs.readFileSync(modulePath,"utf8"))));
test("shared legacy core used",()=>{let called=0;const core={evaluateCandidateDecisionBundle(){called++;return{valid:true,decision:"BLOCK",decisionSource:"CORE",reason:"WAIT_SIGNAL",evidence:{},debug:{signal:"WAIT",price:1,source:{total:0},validation:{acceptedTotal:0},direction:{matchedTotal:0},priceSide:{accepted:0},distance:{accepted:0},quality:{accepted:0},consumed:{rejected:0}}};}};load(builder(),core).evaluateHistoricalLegacy(prefix,context());assert.strictEqual(called,1);});
test("live historical same bundle decision",()=>{const x=load(builder()),r=x.evaluateHistoricalLegacy(prefix,context());assert.strictEqual(r.decision,"ALLOW");});
for(const [name,change,reason] of [["signal",{analysis:{signal:"WAIT",marketBias:"NEUTRAL"}},"WAIT_SIGNAL"],["price",{price:null},"INVALID_PRICE"],["zone",{qualifiedPriceZones:{orderBlocks:[],fvgs:[]}},"NO_SOURCE_ZONES"],["zone validation",{qualifiedPriceZones:{orderBlocks:[zone({structureQualified:false})],fvgs:[]}},"NO_VALID_QUALIFIED_ZONES"],["direction",{qualifiedPriceZones:{orderBlocks:[zone({type:"BEARISH"})],fvgs:[]}},"NO_DIRECTION_MATCH"],["price side",{price:1},"ALL_ZONES_INVALID_PRICE_SIDE"],["distance",{price:200},"ALL_CANDIDATES_TOO_FAR"],["quality",{qualifiedPriceZones:{orderBlocks:[zone({structureSignificanceScore:0,dominantQualifiedZone:false,status:"TOUCHED",zoneHeightATR:0,touches:5})],fvgs:[]}},"ALL_CANDIDATES_LOW_QUALITY"]])test(name+" filter parity",()=>{const r=load(builder(input(change))).evaluateHistoricalLegacy(prefix,context());assert.deepStrictEqual([r.decision,r.reason],["BLOCK",reason]);});
test("consumed filter parity",()=>{const first=load(builder()).evaluateHistoricalLegacy(prefix,context()),second=load(builder()).evaluateHistoricalLegacy(prefix,context({consumedCandidateKeys:[first.candidateKey]}));assert.deepStrictEqual([first.decision,second.decision,second.reason],["ALLOW","BLOCK","ALL_CANDIDATES_CONSUMED"]);});
test("filter change changes decision",()=>assert.deepStrictEqual([load(builder()).evaluateHistoricalLegacy(prefix,context()).decision,load(builder(input({price:200}))).evaluateHistoricalLegacy(prefix,context()).decision],["ALLOW","BLOCK"]));
test("insufficient warmup fail closed",()=>{const p=prefix.slice(0,199),c=context({evaluationIndex:198,evaluationCloseTime:p[198].closeTime});assert.strictEqual(load(builder()).evaluateHistoricalLegacy(p,c).reason,"INSUFFICIENT_WARMUP");});
test("missing builder fail closed",()=>assert.strictEqual(load(null).evaluateHistoricalLegacy(prefix,context()).reason,"LEGACY_INPUT_BUILDER_UNAVAILABLE"));
test("builder exception fail closed",()=>assert.strictEqual(load({buildHistoricalInput(){throw Error("x");}}).evaluateHistoricalLegacy(prefix,context()).reason,"LEGACY_INPUT_BUILDER_EXCEPTION"));
test("malformed builder fail closed",()=>assert.strictEqual(load({buildHistoricalInput(){return{};}}).evaluateHistoricalLegacy(prefix,context()).reason,"LEGACY_INPUT_BUNDLE_MALFORMED"));
test("missing MTF builder reason propagates unavailable",()=>assert.strictEqual(load({buildHistoricalInput(){return{valid:false,status:"MTF_UNAVAILABLE",error:"MTF_DATA_UNAVAILABLE",warnings:[]};}}).evaluateHistoricalLegacy(prefix,context()).decision,"UNAVAILABLE"));
test("future HTF rejected",()=>{const future={...prefix[199],openTime:prefix[199].closeTime+1,closeTime:prefix[199].closeTime+900000};assert.strictEqual(load(builder()).evaluateHistoricalLegacy(prefix,context({higherTimeframeCandles:[future]})).reason,"FUTURE_DATA_SUSPECTED");});
test("look ahead rejected",()=>{const p=prefix.concat(candle(200));assert.strictEqual(load(builder()).evaluateHistoricalLegacy(p,context()).decision,"UNAVAILABLE");});
test("core exception fail closed",()=>assert.strictEqual(load(builder(),{evaluateCandidateDecisionBundle(){throw Error("x");}}).evaluateHistoricalLegacy(prefix,context()).reason,"LEGACY_SHARED_CORE_EXCEPTION"));
test("malformed core fail closed",()=>assert.strictEqual(load(builder(),{evaluateCandidateDecisionBundle(){return{};}}).evaluateHistoricalLegacy(prefix,context()).reason,"LEGACY_SHARED_CORE_MALFORMED"));
test("unexpected reason rejected",()=>{const core={evaluateCandidateDecisionBundle(){return{valid:true,decision:"BLOCK",decisionSource:"CORE",reason:"MADE_UP",evidence:{},debug:{}};}};assert.strictEqual(load(builder(),core).evaluateHistoricalLegacy(prefix,context()).reason,"LEGACY_SHARED_CORE_MALFORMED");});
test("ALLOW passes filters",()=>{const r=load(builder()).evaluateHistoricalLegacy(prefix,context());assert.ok(r.decision==="ALLOW"&&r.filterResults.every(x=>x.passed));});
test("BLOCK carries real reason",()=>assert.strictEqual(load(builder(input({analysis:{signal:"WAIT"}}))).evaluateHistoricalLegacy(prefix,context()).reason,"WAIT_SIGNAL"));
test("duplicate consumed keys rejected",()=>assert.strictEqual(load(builder()).evaluateHistoricalLegacy(prefix,context({consumedCandidateKeys:["A","A"]})).decision,"UNAVAILABLE"));
test("candidate key deterministic",()=>{const x=load(builder());assert.strictEqual(x.evaluateHistoricalLegacy(prefix,context()).candidateKey,x.evaluateHistoricalLegacy(prefix,context()).candidateKey);});
test("filter result schema",()=>load(builder()).evaluateHistoricalLegacy(prefix,context()).filterResults.forEach(x=>assert.deepStrictEqual(Object.keys(x).sort(),["key","passed","actual","expected","reason"].sort())));
test("output contract",()=>["valid","error","schemaVersion","decision","decisionSource","evidence","reason","candidateKey","filterResults","warnings","builderStatus"].forEach(k=>assert.ok(Object.hasOwn(load(builder()).evaluateHistoricalLegacy(prefix,context()),k))));
test("no secrets in output",()=>assert.ok(!/(apiKey|username|computerPath|rawGlobalState)/i.test(JSON.stringify(load(builder()).evaluateHistoricalLegacy(prefix,context())))));
test("consumed input unchanged",()=>{const keys=[];load(builder()).evaluateHistoricalLegacy(prefix,context({consumedCandidateKeys:keys}));assert.deepStrictEqual(keys,[]);});
test("threshold constants absent evaluator",()=>assert.ok(!/MIN_QUALITY|MAX_DISTANCE/.test(fs.readFileSync(modulePath,"utf8"))));
test("CommonJS fails closed without browser deps",()=>assert.strictEqual(api.evaluateHistoricalLegacy(prefix,context()).decision,"UNAVAILABLE"));
(async()=>{let n=0;for(const t of tests){try{await t.fn();n++;}catch(e){console.error(`FAIL: ${t.name}`);throw e;}}console.log(`Structure Historical Legacy Evaluator tests passed: ${tests.length} scenarios, ${n} assertions.`);})().catch(e=>{console.error(e);process.exitCode=1;});
