(function(root,factory){"use strict";var deps=typeof module==="object"&&module.exports?{assessment:require("./structureShadowAssessment.js"),plan:require("./structureShadowObservationPlan.js"),analyzer:require("./structureShadowMismatchAnalyzer.js")}:{assessment:root&&root.HNDStructureShadowAssessment,plan:root&&root.HNDStructureShadowObservationPlan,analyzer:root&&root.HNDStructureShadowMismatchAnalyzer};var api=factory(deps);if(typeof module==="object"&&module.exports)module.exports=api;if(root&&typeof root==="object")root.HNDStructurePaperTrialReadinessGate=api;}(typeof window!=="undefined"?window:null,function(deps){"use strict";
var SCHEMA="HND_STRUCTURE_PAPER_TRIAL_READINESS_V1",SOURCE="HND_STRUCTURE_SHADOW_TELEMETRY_V1",DISCLAIMER="Diagnostic eligibility only; this result does not enable paper trading, entries, or real orders.";
var DEFAULT={requireObservationCriteriaMet:true,requireObservationTargetsMet:true,maxFailureCount:0,maxHighPriorityReviewCount:0,maxMismatchRate:5,requireOperatorAcknowledgement:true};
function clone(v){return v===undefined?undefined:JSON.parse(JSON.stringify(v));}function exact(v,f){if(!v||typeof v!=="object"||Array.isArray(v))return false;var k=Object.keys(v).sort(),e=f.slice().sort();return k.length===e.length&&e.every(function(x,i){return k[i]===x;});}
function validPolicy(p){return exact(p,Object.keys(DEFAULT))&&["requireObservationCriteriaMet","requireObservationTargetsMet","requireOperatorAcknowledgement"].every(function(k){return typeof p[k]==="boolean";})&&["maxFailureCount","maxHighPriorityReviewCount"].every(function(k){return Number.isSafeInteger(p[k])&&p[k]>=0;})&&typeof p.maxMismatchRate==="number"&&Number.isFinite(p.maxMismatchRate)&&p.maxMismatchRate>=0&&p.maxMismatchRate<=100;}
function validContext(c){return exact(c,["diagnosticsReviewed","acknowledgedAt"])&&typeof c.diagnosticsReviewed==="boolean"&&(c.diagnosticsReviewed?Number.isSafeInteger(c.acknowledgedAt)&&c.acknowledgedAt>0:c.acknowledgedAt===null);}
function base(error,status,policy,context){return{valid:false,error:error,schemaVersion:SCHEMA,sourceSchemaVersion:null,status:status,eligibleForPaperTrial:false,policy:policy||null,operatorContext:context||null,checks:[],failedChecks:[],assessmentStatus:null,observationPlanStatus:null,analyzerStatus:null,observationCount:0,comparableCount:0,completedCellCount:0,cellCount:0,failureCount:0,highPriorityReviewCount:0,mismatchCount:0,mismatchRate:null,warnings:[],disclaimer:DISCLAIMER};}
function evaluateReadiness(snapshot,operatorContext,policy){var p,c,valid,a,o,m;try{p=clone(policy===undefined?DEFAULT:policy);c=clone(operatorContext);}catch(e){return base("INVALID_INPUT","INVALID_INPUT",null,null);}if(!validPolicy(p)||!validContext(c))return base("INVALID_INPUT","INVALID_INPUT",p,c);if(!deps.assessment||typeof deps.assessment.validateSnapshot!=="function"||typeof deps.assessment.assessSnapshot!=="function"||!deps.plan||typeof deps.plan.evaluateProgress!=="function"||!deps.analyzer||typeof deps.analyzer.analyzeSnapshot!=="function")return base("DEPENDENCY_FAILURE","DEPENDENCY_FAILURE",p,c);
try{valid=deps.assessment.validateSnapshot(snapshot);if(!valid||valid.valid!==true)return base(valid&&valid.error||"INVALID_SNAPSHOT","INVALID_INPUT",p,c);a=deps.assessment.assessSnapshot(snapshot);o=deps.plan.evaluateProgress(snapshot);m=deps.analyzer.analyzeSnapshot(snapshot);}catch(e){return base("DEPENDENCY_FAILURE","DEPENDENCY_FAILURE",p,c);}
var assessmentStatuses=["INVALID_SNAPSHOT","INVALID_CRITERIA","INSUFFICIENT_DATA","REVIEW_REQUIRED","OBSERVATION_CRITERIA_MET"],planStatuses=["INVALID_SNAPSHOT","INVALID_PLAN","NOT_STARTED","IN_PROGRESS","TARGETS_MET"],analyzerStatuses=["INVALID_SNAPSHOT","NO_OBSERVATIONS","NO_COMPARABLE","MATCH_ONLY","REVIEW_ITEMS_FOUND","FAILURES_FOUND"];
if(!a||a.valid!==true||assessmentStatuses.indexOf(a.status)<0||!o||o.valid!==true||planStatuses.indexOf(o.status)<0||!m||m.valid!==true||analyzerStatuses.indexOf(m.status)<0||!Number.isSafeInteger(m.failureCount)||!Number.isSafeInteger(m.mismatchCount)||!Number.isSafeInteger(o.completedCellCount)||!Number.isSafeInteger(o.cellCount))return base("DEPENDENCY_FAILURE","DEPENDENCY_FAILURE",p,c);
var high=(m.byPriority||[]).find(function(x){return x.key==="HIGH";});var highCount=high&&Number.isSafeInteger(high.count)?high.count:0;var checks=[
{key:"SNAPSHOT_VALID",actual:true,expected:true,passed:true,blocking:true},
{key:"OBSERVATION_CRITERIA_MET",actual:a.status,expected:"OBSERVATION_CRITERIA_MET",passed:!p.requireObservationCriteriaMet||a.status==="OBSERVATION_CRITERIA_MET",blocking:p.requireObservationCriteriaMet},
{key:"OBSERVATION_TARGETS_MET",actual:o.status,expected:"TARGETS_MET",passed:!p.requireObservationTargetsMet||o.status==="TARGETS_MET",blocking:p.requireObservationTargetsMet},
{key:"FAILURE_COUNT",actual:m.failureCount,expected:p.maxFailureCount,passed:m.failureCount<=p.maxFailureCount,blocking:true},
{key:"HIGH_PRIORITY_REVIEW_COUNT",actual:highCount,expected:p.maxHighPriorityReviewCount,passed:highCount<=p.maxHighPriorityReviewCount,blocking:true},
{key:"MISMATCH_RATE",actual:m.mismatchRate,expected:p.maxMismatchRate,passed:m.mismatchRate!==null&&Number.isFinite(m.mismatchRate)&&m.mismatchRate<=p.maxMismatchRate,blocking:true},
{key:"OPERATOR_ACKNOWLEDGEMENT",actual:c.diagnosticsReviewed,expected:true,passed:!p.requireOperatorAcknowledgement||c.diagnosticsReviewed===true,blocking:p.requireOperatorAcknowledgement}];
var status=!checks[1].passed?"LOCKED_INSUFFICIENT_DATA":!checks[2].passed?"LOCKED_OBSERVATION_TARGETS":!checks[3].passed?"LOCKED_FAILURES_PRESENT":!checks[4].passed?"LOCKED_HIGH_PRIORITY_REVIEW":!checks[5].passed?"LOCKED_MISMATCH_RATE":!checks[6].passed?"LOCKED_OPERATOR_ACKNOWLEDGEMENT":"ELIGIBLE_FOR_PAPER_TRIAL_REVIEW";
return clone({valid:true,error:null,schemaVersion:SCHEMA,sourceSchemaVersion:SOURCE,status:status,eligibleForPaperTrial:status==="ELIGIBLE_FOR_PAPER_TRIAL_REVIEW",policy:p,operatorContext:c,checks:checks,failedChecks:checks.filter(function(x){return!x.passed;}).map(function(x){return x.key;}),assessmentStatus:a.status,observationPlanStatus:o.status,analyzerStatus:m.status,observationCount:m.observationCount,comparableCount:m.comparableCount,completedCellCount:o.completedCellCount,cellCount:o.cellCount,failureCount:m.failureCount,highPriorityReviewCount:highCount,mismatchCount:m.mismatchCount,mismatchRate:m.mismatchRate,warnings:[],disclaimer:DISCLAIMER});}
return{getSchemaVersion:function(){return SCHEMA;},getVocabulary:function(){return clone({schemaVersion:SCHEMA,sourceSchemaVersion:SOURCE,statuses:["INVALID_INPUT","DEPENDENCY_FAILURE","LOCKED_INSUFFICIENT_DATA","LOCKED_OBSERVATION_TARGETS","LOCKED_FAILURES_PRESENT","LOCKED_HIGH_PRIORITY_REVIEW","LOCKED_MISMATCH_RATE","LOCKED_OPERATOR_ACKNOWLEDGEMENT","ELIGIBLE_FOR_PAPER_TRIAL_REVIEW"]});},getDefaultPolicy:function(){return clone(DEFAULT);},evaluateReadiness:evaluateReadiness};}));
